### ISSUE TITLE
folder_id ILLEGAL_FIELD when trying to create video in a given folder

### ISSUE THREAD

**Issue by christopherobin** [brightcove/PHP-API-Wrapper#10]
When trying to create a video with a certain folder id the API call fails with the following:

```
Invalid status code: expected 200-299, got 422.\n\n[ {\n  \"error_code\" : \"VALIDATION_ERROR\",\n  \"message\" : \"folder_id: ILLEGAL_FIELD\"\n} ]
```

The PHP code encountering the issue looks like this:

```php
use Brightcove\API\Client;
use Brightcove\API\CMS;
use Brightcove\Object\Video\Video;

$brightcove_cms = new CMS(Client::authorize($client_id, $secret), $account_id);
$video = new Video();
$video->setName($filename);
// $folder_id is a 24 char alphanum id taken directly from the Brightcove interface
$video->setFolderId($folder_id);
$bc_video = $brightcove_cms->createVideo($video);
```

**Comment by janmashat** [comment]
This was working at the time of implementation, so something must have changed in the API. We don't have the bandwidth to fix it in the near future, but pull requests are always welcome.

**Comment by janmashat** [comment]
Folder operations are not fully implemented in the current wrapper. If this feature is business critical for your organization, please contact your Brightcove account manager for further support.
