### ISSUE TITLE
Analytics API

### ISSUE THREAD

**Issue by skynet** [brightcove/PHP-API-Wrapper#13]
Would this work for Analytics API?

**Comment by skynet** [comment]
And does anyone have a stupid simple example connecting to the Brighcove Analytics API to retrieve a list of videos based on a search criteria?

All I could find is a proxy script: http://docs.brightcove.com/en/video-cloud/analytics-api/getting-started/api-overview.html

**Comment by janmashat** [comment]
This wrapper currently supports only Dynamic Ingest API, CMS API, and Player Management API. If you require further assistance, please contact your Brightcove account manager.
