### ISSUE TITLE
Base Fields Error

### ISSUE THREAD

**Issue by tlovett1** [brightcove/PHP-API-Wrapper#14]
I am getting the following error with version 0.6 when I try to upload a new video:
`LogicException: Getting the base fields is not supported for entity type Brightcove API Client. in Drupal\Core\Entity\EntityFieldManager->buildBaseFieldDefinitions() (line 199 of /var/www/drupalvm/drupal/core/lib/Drupal/Core/Entity/EntityFieldManager.php).`

I am running Drupal 8.1.1. I am running Brightcove Video Connect 8.x-1.0

**Comment by janmashat** [comment]
Please reopen this ticket in the appropriate channel https://www.drupal.org/project/issues/brightcove and include step-by-step instructions on how to reproduce the issue - as we have conducted extensive testing with the versions you mentioned and didn't encounter any problems.
