### ISSUE TITLE
PM::listPlayers() returns status code 401

### ISSUE THREAD

**Issue by jazzdrive3** [brightcove/PHP-API-Wrapper#17]
Using valid "read" API credentials, in the context of a CMS, we always get an "Invalid status code: 401". 

"Could not authorize the requested video cloud operation with provided token"

Getting a list of videos and video fields works fine.

I couldn't find any player commands in the API docs. Could it be this command is no longer valid?

**Comment by janmashat** [comment]
Do you still get the error after enabling **all** permissions for that API client, not only read?

**Comment by jazzdrive3** [comment]
Ah, you're also the maintainer of the Drupal module. Cool. Based on your response elsewhere, this can probably be closed.
