### ISSUE TITLE
Organization

### ISSUE THREAD

**Issue by jspizziri** [brightcove/PHP-API-Wrapper#2]
Also, I would suggest organizing the project a bit differently. 

For instance put all the test classes in a Test folder, and use namespaces and so on. Perhaps putt all "brightcove_" files in a root Brightcove folder and use that as the root namespace. And only put one "class/interface" per file and rename the files to represent the classes they actually contain.

What is the likelyhood that something like this will be done?

**Comment by tamasd** [comment]
Thanks for your pull request, I finished the remaining work (some minor stuff + making the tests work).

**Comment by jspizziri** [comment]
Thank you very much! 

I'm working on creating a Symfony Bundle wrapping this lib if you're interested: https://github.com/lighthousecatholicmedia/LCMBrightcoveBundle

Also, could you add a new git tag? Composer is much happier when you can specify a release version. As you can see, I have to target `@dev` in order to install the library.

Also, I have a question I'm wondering if you could answer for me. We're using this SDK for a webapp we're building. How do we use this api to stream video to the client on a 'restricted per user' basis?

Anyways, thanks for merging this in! It's going to be very helpful to me!

**Comment by tamasd** [comment]
Currently @KonczGabor is working on some tests for the playlist, when he's finished there will be a new release.

Do you want to embed the video somehow?

**Comment by jspizziri** [comment]
Awesome.

Yeah I'm effectively trying to embed it. We have an application where people buy access to specific videos. We keep track of what videos they purchase in our application. We'll store the Brightcove video ID on our side as well. When a user wants to view a video we will check their entitlements, and fetch the video (preferable a one time tokenized stream link) via the API, and render it clientside.

Thanks for your help.
