### ISSUE TITLE
Playback API

### ISSUE THREAD

**Issue by phil-s** [brightcove/PHP-API-Wrapper#20]
Is there any intention of adding support for making Playback API requests?

It seems like an unexpected omission.

**Comment by janmashat** [comment]
Playback API wasn't in the scope of the original development and I don't expect it to be added in the near future, as our priority at the moment is to provide better endpoint coverage for CMS API and Dynamic Ingest API.

If this feature is business critical for your organization, please open a discussion with your Brightcove account manager or Brightcove Global Services.
