### ISSUE TITLE
Error 400

### ISSUE THREAD

**Issue by ezraw** [brightcove/PHP-API-Wrapper#24]
Hi,

I am receiving a 400 response code. I've ensured the API application has all permissions enabled. Is there documentation for the error codes? I've been unable to find it.

> Brightcove\API\Exception\APIException: Invalid status code: expected 200-299, got 400. in Brightcove\API\Client->request() (line 321 of /sites/all/libraries/PHP-API-Wrapper/lib/Brightcove/API/Client.php).

**Comment by janmashat** [comment]
The error codes for CMS API are listed here:
https://docs.brightcove.com/en/video-cloud/cms-api/references/error-messages.html

Debug logging can be enabled in lib/Brightcove/API/Client.php, ex:
`public static $debugRequests = "/tmp/bc.log";`

**Comment by ezraw** [comment]
Thanks! I'll take this specific issue to the Drupal issue queue then.
