### ISSUE TITLE
How to get FLV URL with the new API?

### ISSUE THREAD

**Issue by F3L1X79** [brightcove/PHP-API-Wrapper#28]
With the old API, it was possible to get the FLV URL like:

```
$bc = new BCMAPI(
	    	'xxx', 'xxx'
	    );
		$searchParams = array(
	        'video_id' => $id,
	        'media_delivery' => 'HTTP',
	        'video_fields' => 'FLVURL'
	    );
		$cbf = $bc->find('videobyid', $searchParams);
		$flvurl = $cbf->{'FLVURL'};
```

With the new API I tried:
```
                    $CLIENT_ID = 'xxx';
                    $CLIENT_SECRET = 'xxx';
                    $ACCOUNT = 'xxx';

                        $CLIENT = \Brightcove\API\Client::authorize($CLIENT_ID, $CLIENT_SECRET);
                        $CMS = new \Brightcove\API\CMS($CLIENT, $ACCOUNT);

                        $cms_video = $CMS->getVideo($id);
                        var_dump($cms_video->link);
```

But the link attribute is always NULL.
Any help is greatly appreciated.

**Comment by janmashat** [comment]
The new API doesn't support FLVURL as per https://support.brightcove.com/migrating-legacy-apis-catalog-apis

**Comment by F3L1X79** [comment]
Any workaround, or any way to retrieve this information somewhere?

**Comment by janmashat** [comment]
You can retrieve the information through the Media API, while it's still available:
> On December 31, 2017, the “read” methods of the Media API will be fully retired.
https://support.brightcove.com/changes-video-cloud-service

**Comment by F3L1X79** [comment]
Brightcove API is a real pain, seriously.
