### ISSUE TITLE
Error: Class 'Brightcove\API\Client' not found

### ISSUE THREAD

**Issue by MayraU** [brightcove/PHP-API-Wrapper#39]
Using a clean drupal 7.64 with php version 7.1.18. Installed Brightcove but the moment i add and save my api keys i get this error on submission:
Error: Class 'Brightcove\API\Client' not found in {closure}() (line 311 of /sites/all/modules/brightcove/brightcove.client.inc).

Using Brightcove Video Connect 7.x-6.5 using Brightcove API Wrapper 1.1.0(https://github.com/brightcove/PHP-API-Wrapper/releases/tag/1.1.0) and also tried 1.0(https://github.com/brightcove/PHP-API-Wrapper/releases/tag/1.0). Both versions gave me the same error.
![library](https://user-images.githubusercontent.com/5068545/52839393-db1a0580-30aa-11e9-949c-00d375db9f62.JPG)

Not sure if I'm missing a step?

**Comment by janmashat** [comment]
This error usually means that the library wasn't installed correctly. How exactly did you install it?
