### ISSUE TITLE
Can you give sample for create video?

### ISSUE THREAD

**Issue by sasiarjun** [brightcove/PHP-API-Wrapper#4]
Can you give sample php code how to use create video and digest request?
Where i can store the meta data file?

**Comment by tamasd** [comment]
A simple example:

    $client = \Brightcove\API\Client::authorize($client_id, $client_secret);
    $cms = new \Brightcove\API\CMS($client, $account);
    $di = new \Brightcove\API\DI($client, $account); 

    $video = new \Brightcove\Object\Video\Video();
    $video->setName("...");
    $video = $cms->createVideo($video);

    $request = \Brightcove\API\Request\IngestRequest::createRequest($url, $profile);
    $di->createIngest($video->getId(), $request);

What kind of metadata file?

**Comment by sasiarjun** [comment]
I thought we need to keep basic video metadata ,cuepoints and custom field
add and update. how i can update these details for appropriate video?

**Comment by tamasd** [comment]
See the documentation of the `Video` class. You can add any kind of metadata that is supported by the CMS API before calling `createVideo()`.

**Comment by sasiarjunan** [comment]
Thank you, worked well.
