### ISSUE TITLE
listVideos combine search giving empty result

### ISSUE THREAD

**Issue by sasiarjun** [brightcove/PHP-API-Wrapper#5]
Hi,
Im searching with following conditions,  
In my account have the video name as "welcome to cloud". and tagged as "manager"  between dates.
But both conditions are returning empty value for listVideo api call. but we have value for both conditions.

1. +name:welcome+updated_at:2015-06-27T00:00:00.000Z..2015-06-30T00:00:00.000Z
2. +tags:manager+updated_at:2015-06-27T00:00:00.000Z..2015-06-30T00:00:00.000Z

Please help me to fix this.

**Comment by sasiarjun** [comment]
Also i asked the support from brightcove, but they are retrieving data using following url 

https://cms.api.brightcove.com/v1/accounts/4317630921001/videos?q=keywords:arcus&q=updated_at:2015-06-27T00:00:00.000Z..2015-06-30T00:00:00.000Z

But how i can use the same?

**Comment by tamasd** [comment]
Set `\Brightcove\API\Client::$debugRequests = "/tmp/bclog.txt";` before making any calls. This turns on the debug log, and will probably help figuring out what is going wrong.
