### ISSUE TITLE
setCustomField giving invalid field error

### ISSUE THREAD

**Issue by sasiarjun** [brightcove/PHP-API-Wrapper#6]
Im sending the following input for custom field 

array(4) { ["field1"]=> string(6) "value1" ["field2"]=> string(6) "value2" ["field3"]=> string(6) "value3" ["field4"]=> string(6) "value4" }

but im getting following error when send the custom field.

Brightcove\API\Exception\APIException
Invalid status code: expected 200-299, got 422.
[ {
"error_code" : "VALIDATION_ERROR",
"message" : "custom_fields.field1: ILLEGAL_FIELD"
} ]

Please help me to fix this issue.

**Comment by janmashat** [comment]
Do you have a 'field1' custom field created on that Brightcove account?

**Comment by sasiarjun** [comment]
No, I didn't , Where i have to create

**Comment by janmashat** [comment]
in Brightcove Video Cloud under account settings

**Comment by sasiarjun** [comment]
Yes, I got it, Its worked good. Is there any API call to create custom fields?

**Comment by janmashat** [comment]
No, creating custom fields hasn't been implemented.

**Comment by sasiarjun** [comment]
Thank you
