### ISSUE TITLE
Unauthorized message 

### ISSUE THREAD

**Issue by sasiarjun** [brightcove/PHP-API-Wrapper#7]
When im trying to ingest the video, Im getting the following error...
Invalid status code: expected 200-299, got 401.
[{"error_code": "UNAUTHORIZED", "message": "Permission denied."}]
But im giving the valid credentials. what  might be the issue?

When im running file as manual its running good, If i put automate(supervisord) job, its giving permission denied error.. Please help me to fix this...

**Comment by tamasd** [comment]
This can be two things:

- Sometimes the authorization fails for no reason. Try making a retry loop.
- Check that your token has all permissions on the https://studio.brightcove.com/products/videocloud/admin/oauthsettings page. Detecting permissions is not supported by the API yet, so failing gracefully is not implemented.
