### ISSUE TITLE
how i get list of our brighcove account ingest profiles?

### ISSUE THREAD

**Issue by sasiarjun** [brightcove/PHP-API-Wrapper#8]
I tried to get list of ingest profiles which is from our account, Please help me to get list of ingest profiles from our brightcove account

following url provided option to get ingest profiles
http://docs.brightcove.com/en/video-cloud/ingest-profiles-api/getting-started/quick-start.html

but this php wrapper how we get the list of ingest profiles.

**Comment by tamasd** [comment]
That API is not implemented yet.
